"""Dynamic crawler and document reader for official Ministry of Trade sources.

The source list is deliberately kept in ``ticaret_sources.json`` so deployments can
add or remove official entry points without changing crawler code.  Sector names,
page titles, document titles and document metadata are always derived from the live
pages; they are not generated by the model or hard-coded into search results.
"""

from __future__ import annotations

import asyncio
import hashlib
import io
import json
import logging
import os
import re
import shutil
# Only fixed, allowlisted text extractors are invoked and shell mode is never enabled.
import subprocess  # nosec B404
import sys
import tempfile
import time
import unicodedata
import zipfile
from collections import OrderedDict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable, Optional
from urllib.parse import parse_qsl, quote, unquote, urlencode, urljoin, urlsplit, urlunsplit

import httpx
from bs4 import BeautifulSoup, Tag
from markitdown import MarkItDown

from bedesten_client import BedestenClient
from security_firewall import validate_outbound_url
from ticaret_models import (
    TicaretCatalog,
    TicaretCatalogStatus,
    TicaretContentMatch,
    TicaretContentSearchResult,
    TicaretDocument,
    TicaretDocumentContent,
    TicaretSearchResult,
    TicaretSource,
)

logger = logging.getLogger(__name__)

_DATE_RE = re.compile(r"\b(?:0?[1-9]|[12]\d|3[01])[./-](?:0?[1-9]|1[0-2])[./-](?:19|20)\d{2}\b")
_YEAR_RE = re.compile(r"\b(?:19|20)\d{2}\b")
_NUMBER_RE = re.compile(
    r"(?:\b(?:19|20)\d{2}\s*/\s*\d+\b|\b(?:Seri\s+No|Sayı(?:\s+No)?|Karar\s+Sayısı)\s*[:：]?\s*[\w./-]+)",
    re.IGNORECASE,
)
_GENERIC_LINK_TEXT = {
    "indir",
    "dosya indir",
    "detay",
    "tiklayiniz",
    "tıklayınız",
    "goruntule",
    "görüntüle",
    "link",
    "buradan",
    "ek",
}
_DOCUMENT_EXTENSIONS = {
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".csv", ".txt",
    ".rtf", ".ppt", ".pptx", ".zip", ".json", ".xml",
}
_OFFICIAL_CONTENT_HOSTS = {
    "ticaret.gov.tr",
    "mevzuat.gov.tr",
    "resmigazete.gov.tr",
}


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _iso_now() -> str:
    return _utc_now().isoformat()


def _clean_text(value: str | None) -> str:
    if not value:
        return ""
    return re.sub(r"\s+", " ", value.replace("\xa0", " ")).strip()


def _search_key(value: str | None) -> str:
    value = (value or "").casefold().replace("ı", "i")
    decomposed = unicodedata.normalize("NFKD", value)
    return "".join(ch for ch in decomposed if not unicodedata.combining(ch))


def _stable_id(source_id: str, url: str, suffix: str = "") -> str:
    digest = hashlib.sha256(f"{source_id}\0{url}\0{suffix}".encode("utf-8")).hexdigest()
    return f"ticaret_{digest[:24]}"


def _canonical_page_url(url: str) -> str:
    parsed = urlsplit(url)
    path = quote(unquote(parsed.path or "/"), safe="/%:@")
    # The Ministry uses `s` for pagination. Other tracking parameters are not
    # part of a page's identity and would create crawl loops.
    query = urlencode(sorted((k, v) for k, v in parse_qsl(parsed.query) if k.lower() in {"s", "page"}))
    if path != "/" and not path.endswith("/"):
        canonical_path = path.rstrip("/")
    else:
        canonical_path = path
    return urlunsplit((parsed.scheme.lower() or "https", parsed.netloc.lower(), canonical_path or "/", query, ""))


def _canonical_document_url(url: str) -> str:
    parsed = urlsplit(url)
    path = quote(unquote(parsed.path or "/"), safe="/%:@")
    return urlunsplit((parsed.scheme.lower() or "https", parsed.netloc.lower(), path, parsed.query, ""))


def _file_type(url: str, content_type: str | None = None) -> str:
    suffix = Path(unquote(urlsplit(url).path)).suffix.lower()
    if suffix:
        return suffix.lstrip(".")
    content_type = (content_type or "").lower()
    for marker, label in (
        ("pdf", "pdf"), ("word", "docx"), ("spreadsheet", "xlsx"),
        ("excel", "xlsx"), ("csv", "csv"), ("json", "json"),
        ("xml", "xml"), ("html", "html"), ("text", "txt"),
    ):
        if marker in content_type:
            return label
    return "link"


def _sniff_document_extension(data: bytes, content_type: str = "") -> str:
    """Resolve missing or misleading document metadata without trusting filenames alone."""
    media_type = content_type.lower().split(";", 1)[0].strip()
    by_media_type = {
        "application/pdf": ".pdf",
        "application/msword": ".doc",
        "application/vnd.ms-excel": ".xls",
        "application/vnd.ms-powerpoint": ".ppt",
        "application/rtf": ".rtf",
        "text/rtf": ".rtf",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx",
        "application/zip": ".zip",
    }
    if media_type in by_media_type:
        return by_media_type[media_type]
    sample = data[:4096].lstrip()
    if data.startswith(b"%PDF-"):
        return ".pdf"
    if data.startswith(b"PK\x03\x04"):
        return ".zip"
    if data.startswith(bytes.fromhex("D0CF11E0A1B11AE1")):
        # OLE compound documents need their HTTP metadata to distinguish
        # Word, Excel and PowerPoint. Unknown OLE files are handled safely.
        return by_media_type.get(media_type, ".ole")
    if sample.startswith((b"<!DOCTYPE html", b"<!doctype html", b"<html", b"<HTML")):
        return ".html"
    if sample.startswith(b"{\\rtf"):
        return ".rtf"
    return ""


def _is_official_content_host(hostname: str | None) -> bool:
    host = (hostname or "").lower().rstrip(".")
    return any(host == allowed or host.endswith(f".{allowed}") for allowed in _OFFICIAL_CONTENT_HOSTS)


def _is_generic_link_text(value: str) -> bool:
    key = _search_key(_clean_text(value)).strip(" .:-")
    return not key or key in _GENERIC_LINK_TEXT or len(key) <= 2


class TicaretApiClient:
    """Crawl, search and read public Ministry of Trade information."""

    def __init__(
        self,
        *,
        config_path: str | Path | None = None,
        sync_interval_seconds: int | None = None,
        request_timeout: float = 35.0,
        max_download_bytes: int = 45 * 1024 * 1024,
    ) -> None:
        configured_path = config_path or os.environ.get("TICARET_SOURCES_FILE")
        if configured_path:
            self._config_path = Path(configured_path)
        else:
            source_tree_path = Path(__file__).with_name("ticaret_sources.json")
            installed_data_path = Path(sys.prefix) / "ticaret_sources.json"
            self._config_path = source_tree_path if source_tree_path.exists() else installed_data_path
        config = json.loads(self._config_path.read_text(encoding="utf-8"))
        self.sources = [TicaretSource.model_validate(item) for item in config.get("sources", [])]

        extra_sources = os.environ.get("TICARET_EXTRA_SOURCES_JSON")
        if extra_sources:
            self.sources.extend(TicaretSource.model_validate(item) for item in json.loads(extra_sources))

        configured_interval = sync_interval_seconds or int(
            os.environ.get("TICARET_SYNC_INTERVAL_SECONDS", config.get("sync_interval_seconds", 21600))
        )
        self.sync_interval_seconds = max(300, configured_interval)
        self.priority_sync_interval_seconds = max(
            300,
            int(
                os.environ.get(
                    "TICARET_PRIORITY_SYNC_INTERVAL_SECONDS",
                    config.get("priority_sync_interval_seconds", 3600),
                )
            ),
        )
        self.max_download_bytes = max_download_bytes
        self._http = httpx.AsyncClient(
            headers={
                "User-Agent": "TicaretBilgiMCP/1.0 (+public-government-information-indexer)",
                "Accept-Language": "tr-TR,tr;q=0.9,en;q=0.6",
            },
            follow_redirects=False,
            timeout=httpx.Timeout(request_timeout),
            limits=httpx.Limits(max_connections=8, max_keepalive_connections=6),
        )
        self._converter = MarkItDown()
        self._bedesten = BedestenClient()
        self._request_semaphore = asyncio.Semaphore(8)
        self._catalog: TicaretCatalog | None = None
        self._catalog_monotonic: float = 0.0
        self._last_full_sync_monotonic: float = 0.0
        self._sync_lock = asyncio.Lock()
        self._syncing = False
        self._next_sync_at: datetime | None = None
        self._content_cache: OrderedDict[str, tuple[float, str, str, list[str]]] = OrderedDict()
        self._content_cache_ttl = 3600
        self._content_cache_limit = 24

    async def close(self) -> None:
        await self._http.aclose()
        await self._bedesten.close()

    async def _get(self, url: str) -> httpx.Response:
        last_error: Exception | None = None
        for attempt in range(2):
            try:
                current_url = url
                for _ in range(6):
                    validate_outbound_url(current_url, allowed_hosts=_OFFICIAL_CONTENT_HOSTS)
                    async with self._request_semaphore:
                        response = await self._http.get(current_url)
                    if not response.is_redirect:
                        break
                    location = response.headers.get("location", "")
                    if not location:
                        raise ValueError("Resmî kaynak yönlendirmesi hedefsiz")
                    current_url = urljoin(str(response.url), location)
                else:
                    raise ValueError("Resmî kaynak çok fazla yönlendirme yaptı")
                response.raise_for_status()
                return response
            except (httpx.HTTPError, httpx.TimeoutException, ValueError) as exc:
                last_error = exc
                if attempt < 1:
                    await asyncio.sleep(0.35 * (2 ** attempt))
        if last_error is None:  # Defensive guard; the retry loop always assigns an error before reaching this branch.
            raise RuntimeError("Resmî kaynak isteği beklenmeyen biçimde tamamlanamadı.")
        raise last_error

    @staticmethod
    def _content_container(soup: BeautifulSoup) -> Tag | BeautifulSoup:
        selectors = (
            ".__wrapper .__zone .__content",
            ".__zone .__content",
            "main article",
            "main",
            "article",
            "[role='main']",
            "#content",
        )
        for selector in selectors:
            found = soup.select_one(selector)
            if isinstance(found, Tag):
                return found
        return soup.body or soup

    @staticmethod
    def _page_heading(soup: BeautifulSoup, content: Tag | BeautifulSoup, fallback_url: str) -> str:
        for selector in (".__header h1", ".__header h2", "main h1", "article h1", "h1", "h2"):
            heading = soup.select_one(selector)
            if heading:
                text = _clean_text(heading.get_text(" ", strip=True))
                if text:
                    return text
        title = _clean_text(soup.title.get_text(" ", strip=True) if soup.title else "")
        if title and title.lower() not in {"t.c. ticaret bakanlığı", "ticaret bakanlığı"}:
            return title
        return _clean_text(unquote(urlsplit(fallback_url).path).rsplit("/", 1)[-1].replace("-", " ")) or "Ticaret Bakanlığı"

    @staticmethod
    def _breadcrumbs(soup: BeautifulSoup) -> list[str]:
        values = []
        for item in soup.select("nav[aria-label='breadcrumb'] li, .breadcrumb li"):
            text = _clean_text(item.get_text(" ", strip=True))
            if text and text not in values and _search_key(text) not in {"ana sayfa", "anasayfa"}:
                values.append(text)
        return values

    @staticmethod
    def _page_updated(soup: BeautifulSoup) -> str | None:
        for node in soup.select(".__header span, time"):
            value = _clean_text(node.get("datetime") or node.get_text(" ", strip=True))
            if _YEAR_RE.search(value):
                return value
        return None

    @staticmethod
    def _matches_source_page(url: str, source: TicaretSource) -> bool:
        parsed = urlsplit(url)
        root = urlsplit(source.url)
        if parsed.hostname != root.hostname:
            return False
        path = unquote(parsed.path).rstrip("/") or "/"
        return any(path == prefix.rstrip("/") or path.startswith(prefix.rstrip("/") + "/") for prefix in source.follow_prefixes)

    @staticmethod
    def _resolve_href(page_url: str, href: str) -> str:
        """Resolve links, including one official subsite's root-relative links without '/'."""
        page = urlsplit(page_url)
        if (page.hostname or "").lower() == "urunkurallari.ticaret.gov.tr" and re.match(r"^(?:tr|en)/", href):
            return urljoin(f"{page.scheme}://{page.netloc}/", href)
        return urljoin(page_url, href)

    @staticmethod
    def _infer_document_type(title: str, section: str, kind: str) -> str:
        types = (
            ("cumhurbaskanligi karari", "Cumhurbaşkanı Kararı"),
            ("bakanlar kurulu karari", "Bakanlar Kurulu Kararı"),
            ("kanun", "Kanun"),
            ("yonetmelik", "Yönetmelik"),
            ("teblig", "Tebliğ"),
            ("genelge", "Genelge"),
            ("karar", "Karar"),
            ("sozlesme", "Sözleşme"),
            ("kilavuz", "Kılavuz"),
            ("rehber", "Rehber"),
            ("rapor", "Rapor"),
            ("bulten", "Bülten"),
            ("istatistik", "İstatistik"),
            ("veri", "Veri"),
        )
        # The title is authoritative. A parent section called "Tebliğler" must
        # not turn a child named "İthalat Rejimi Kararı" into a Tebliğ.
        for haystack in (_search_key(title), _search_key(f"{title} {section}")):
            for marker, label in types:
                if marker in haystack:
                    return label
        return {
            "destek": "Destek Bilgisi",
            "iletisim": "İletişim Bilgisi",
            "ulke_bilgisi": "Ülke/Pazar Bilgisi",
            "yayin": "Yayın",
            "veri": "Veri Kaynağı",
            "rapor": "Rapor/Pazar Bilgisi",
        }.get(kind, "Bilgi Sayfası")

    @staticmethod
    def _row_metadata(anchor: Tag) -> tuple[str, dict[str, Any], str | None, str | None, str | None]:
        row = anchor.find_parent("tr")
        if not row:
            return "", {}, None, None, None
        cells = [_clean_text(cell.get_text(" ", strip=True)) for cell in row.find_all(["th", "td"], recursive=False)]
        table = row.find_parent("table")
        headers: list[str] = []
        if table:
            first_row = table.find("tr")
            if first_row:
                headers = [_clean_text(cell.get_text(" ", strip=True)) for cell in first_row.find_all(["th", "td"], recursive=False)]
        columns = {
            (headers[index] if index < len(headers) and headers[index] else f"column_{index + 1}"): value
            for index, value in enumerate(cells)
            if value
        }
        context = " | ".join(cells)
        date_match = _DATE_RE.search(context)
        number_match = _NUMBER_RE.search(context)
        gazette = None
        for key, value in columns.items():
            if "gazete" in _search_key(key):
                gazette = value
                break
        return context, {"columns": columns}, number_match.group(0) if number_match else None, date_match.group(0) if date_match else None, gazette

    @staticmethod
    def _best_title(anchor: Tag, url: str, row_context: str, heading: str) -> str:
        link_text = _clean_text(anchor.get_text(" ", strip=True))
        if not _is_generic_link_text(link_text):
            return link_text
        if row_context:
            parts = [part.strip() for part in row_context.split("|") if part.strip()]
            non_generic = [part for part in parts if not _is_generic_link_text(part) and not _DATE_RE.fullmatch(part)]
            if non_generic:
                return max(non_generic, key=len)
        parent = anchor.parent
        if parent:
            parent_text = _clean_text(parent.get_text(" ", strip=True))
            parent_text = re.sub(
                r"\b(?:detaylı\s+bilgi\s+için|görüntülemek\s+için|indirmek\s+için|için)?\s*(?:tıklayınız|indir|detay)\.?\s*$",
                "",
                parent_text,
                flags=re.IGNORECASE,
            ).strip(" :-")
            if parent_text and len(parent_text) > 3:
                return parent_text[:300]
        filename = _clean_text(Path(unquote(urlsplit(url).path)).stem.replace("_", " ").replace("-", " "))
        return filename or heading

    def _parse_page(self, source: TicaretSource, page_url: str, html: str) -> tuple[list[str], list[TicaretDocument]]:
        soup = BeautifulSoup(html, "lxml")
        content = self._content_container(soup)
        heading = self._page_heading(soup, content, page_url)
        breadcrumbs = self._breadcrumbs(soup)
        updated_at = self._page_updated(soup)
        section = breadcrumbs[-1] if breadcrumbs else heading
        if _search_key(section) == _search_key(heading) and len(breadcrumbs) > 1:
            section = breadcrumbs[-2]
        subsection = heading if _search_key(heading) != _search_key(section) else None
        content_text = _clean_text(content.get_text(" ", strip=True))

        children: list[str] = []
        documents: list[TicaretDocument] = []

        # Landing pages on ticaret.gov.tr render their cards outside the usual
        # article container.  Discover only same-source descendants from the
        # whole DOM; document extraction remains restricted to the content area
        # so menus and footer links never become fake records.
        for candidate_anchor in soup.select("a[href]"):
            candidate_href = (candidate_anchor.get("href") or "").strip()
            if not candidate_href or candidate_href.startswith(("#", "javascript:", "mailto:", "tel:")):
                continue
            candidate_url = self._resolve_href(page_url, candidate_href)
            if self._matches_source_page(candidate_url, source):
                child = _canonical_page_url(candidate_url)
                if child != _canonical_page_url(page_url) and child not in children:
                    children.append(child)
                    # The overseas organization tree links hundreds of country
                    # records, several of which respond as slow direct PDFs.
                    # Index every discovered official link immediately so full
                    # access does not depend on eagerly downloading each one.
                    candidate_title = _clean_text(candidate_anchor.get_text(" ", strip=True))
                    if source.content_kind == "ulke_bilgisi" and not _is_generic_link_text(candidate_title):
                        identity_parts = urlsplit(child)
                        page_identity = urlunsplit(
                            (identity_parts.scheme, identity_parts.netloc, identity_parts.path, "", "")
                        )
                        candidate_context = _clean_text(
                            candidate_anchor.parent.get_text(" ", strip=True) if candidate_anchor.parent else ""
                        )
                        documents.append(
                            TicaretDocument(
                                id=_stable_id(source.id, page_identity, "page"),
                                title=candidate_title[:500],
                                source_id=source.id,
                                content_kind=source.content_kind,
                                section=heading,
                                document_type=self._infer_document_type(candidate_title, heading, source.content_kind),
                                document_url=child,
                                source_page_url=page_url,
                                file_type=_file_type(child),
                                is_page=True,
                                context=candidate_context[:4000] if candidate_context else None,
                                metadata={"discovered_from": page_url, "lazy_country_record": True},
                            )
                        )

        # The HTML page itself is searchable and readable.  This is important
        # for consolidated legislation, contact lists and data descriptions
        # that do not have a separate download link.
        if len(content_text) >= 40:
            page_identity_parts = urlsplit(page_url)
            page_identity = urlunsplit(
                (page_identity_parts.scheme, page_identity_parts.netloc, page_identity_parts.path, "", "")
            )
            page_id = _stable_id(source.id, page_identity, "page")
            page_type = self._infer_document_type(heading, section, source.content_kind)
            documents.append(
                TicaretDocument(
                    id=page_id,
                    title=heading,
                    source_id=source.id,
                    content_kind=source.content_kind,
                    section=section,
                    subsection=subsection,
                    document_type=page_type,
                    publication_date=updated_at,
                    page_updated_at=updated_at,
                    document_url=page_url,
                    source_page_url=page_url,
                    file_type="html",
                    is_page=True,
                    is_repealed="mulga" in _search_key(f"{heading} {content_text[:1200]}"),
                    context=content_text[:4000],
                    metadata={"breadcrumbs": breadcrumbs},
                )
            )

        anchors: list[Tag] = list(content.select("a[href]"))
        zone = soup.select_one(".__zone")
        if zone:
            anchors.extend(a for a in zone.select(".pagination a[href]") if a not in anchors)

        seen_links: set[str] = set()
        for anchor in anchors:
            raw_href = (anchor.get("href") or "").strip()
            if not raw_href or raw_href.startswith(("#", "javascript:", "mailto:", "tel:")):
                continue
            absolute = self._resolve_href(page_url, raw_href)
            parsed = urlsplit(absolute)
            if parsed.scheme not in {"http", "https"}:
                continue

            if self._matches_source_page(absolute, source):
                child = _canonical_page_url(absolute)
                if child != _canonical_page_url(page_url) and child not in children:
                    children.append(child)
                continue

            document_url = _canonical_document_url(absolute)
            if document_url in seen_links:
                continue
            seen_links.add(document_url)

            row_context, metadata, number, publication_date, gazette = self._row_metadata(anchor)
            title = self._best_title(anchor, document_url, row_context, heading)
            anchor_label = _clean_text(anchor.get_text(" ", strip=True))
            path_suffix = Path(unquote(parsed.path)).suffix.lower()

            # Ignore ordinary navigation links that escaped the content area;
            # keep official downloads, legislation links and descriptive links.
            official_host = _is_official_content_host(parsed.hostname)
            if not official_host and path_suffix not in _DOCUMENT_EXTENSIONS and _is_generic_link_text(anchor_label):
                continue

            document_type = self._infer_document_type(title, f"{section} {heading}", source.content_kind)
            context = row_context or _clean_text(anchor.parent.get_text(" ", strip=True) if anchor.parent else "")
            documents.append(
                TicaretDocument(
                    id=_stable_id(source.id, document_url),
                    title=title[:500],
                    source_id=source.id,
                    content_kind=source.content_kind,
                    section=section,
                    subsection=subsection,
                    document_type=document_type,
                    number=number,
                    publication_date=publication_date,
                    official_gazette=gazette,
                    page_updated_at=updated_at,
                    document_url=document_url,
                    source_page_url=page_url,
                    file_type=_file_type(document_url),
                    is_page=False,
                    is_repealed="mulga" in _search_key(f"{title} {context}"),
                    attachment_label=anchor_label if anchor_label else None,
                    context=context[:4000] if context else None,
                    metadata={**metadata, "breadcrumbs": breadcrumbs},
                )
            )
        return children, documents

    def _parse_feed(self, source: TicaretSource, feed_url: str, xml: str) -> list[TicaretDocument]:
        """Parse official RSS/Atom items as independently searchable records."""
        soup = BeautifulSoup(xml, "xml")
        documents: list[TicaretDocument] = []
        for item in soup.find_all(["item", "entry"]):
            title = _clean_text(item.find("title").get_text(" ", strip=True) if item.find("title") else "")
            link_node = item.find("link")
            link = ""
            if link_node:
                link = _clean_text(link_node.get("href") or link_node.get_text(" ", strip=True))
            if not title or not link:
                continue
            document_url = urljoin(feed_url, link)
            parsed = urlsplit(document_url)
            if _is_official_content_host(parsed.hostname):
                document_url = urlunsplit(("https", parsed.netloc, parsed.path, parsed.query, ""))
            description_node = item.find("description") or item.find("summary") or item.find("content")
            raw_description = description_node.get_text(" ", strip=True) if description_node else ""
            context = _clean_text(BeautifulSoup(raw_description, "lxml").get_text(" ", strip=True))
            date_node = item.find("pubDate") or item.find("published") or item.find("updated")
            publication_date = _clean_text(date_node.get_text(" ", strip=True)) if date_node else None
            documents.append(
                TicaretDocument(
                    id=_stable_id(source.id, _canonical_document_url(document_url)),
                    title=title,
                    source_id=source.id,
                    content_kind=source.content_kind,
                    section="Ticaret Müşavirliklerimizden Güncel Bilgiler",
                    document_type=self._infer_document_type(title, "", source.content_kind),
                    publication_date=publication_date,
                    document_url=document_url,
                    source_page_url=feed_url,
                    file_type="html",
                    is_page=False,
                    context=context[:4000] if context else None,
                    metadata={"feed": feed_url},
                )
            )
        return documents

    async def _crawl_source(
        self,
        source: TicaretSource,
        *,
        partial: bool = False,
    ) -> tuple[int, list[TicaretDocument], list[str]]:
        frontier = [_canonical_page_url(source.url)]
        seen: set[str] = set()
        documents: list[TicaretDocument] = []
        errors: list[str] = []
        concurrency = 5

        while frontier and len(seen) < source.max_pages:
            batch: list[str] = []
            while frontier and len(batch) < concurrency and len(seen) + len(batch) < source.max_pages:
                url = frontier.pop(0)
                if url not in seen and url not in batch:
                    batch.append(url)
            if not batch:
                break

            async def fetch_page(url: str) -> tuple[str, str | None, str | None, str, str | None]:
                try:
                    response = await self._get(url)
                    content_type = response.headers.get("content-type", "").lower()
                    resolved_url = str(response.url)
                    if "html" not in content_type and "xml" not in content_type and "rss" not in content_type:
                        return url, None, content_type, resolved_url, None
                    return url, response.text, content_type, resolved_url, None
                except Exception as exc:  # keep other sources usable
                    return url, None, None, url, f"{type(exc).__name__}: {exc}"

            results = await asyncio.gather(*(fetch_page(url) for url in batch))
            for url, html, content_type, resolved_url, error in results:
                seen.add(url)
                if error:
                    errors.append(f"{source.id}: {url}: {error}")
                    continue
                if html is None:
                    disposition = content_type or ""
                    empty_soup = BeautifulSoup("", "lxml")
                    title = self._page_heading(empty_soup, empty_soup, resolved_url)
                    documents.append(
                        TicaretDocument(
                            id=_stable_id(source.id, _canonical_document_url(resolved_url)),
                            title=title,
                            source_id=source.id,
                            content_kind=source.content_kind,
                            section=title,
                            document_type=self._infer_document_type(title, source.id, source.content_kind),
                            document_url=resolved_url,
                            source_page_url=source.url,
                            file_type=_file_type(resolved_url, disposition),
                            is_page=False,
                            context="Resmî kaynak ağacında doğrudan belge olarak yayımlanan içerik.",
                            metadata={"content_type": disposition, "discovered_url": url},
                        )
                    )
                    continue
                try:
                    if "xml" in (content_type or "") or "rss" in (content_type or ""):
                        documents.extend(self._parse_feed(source, url, html))
                        continue
                    children, page_documents = self._parse_page(source, url, html)
                    documents.extend(page_documents)
                    for child in children:
                        if child not in seen and child not in frontier:
                            frontier.append(child)
                except Exception as exc:
                    errors.append(f"{source.id}: {url}: ayrıştırma hatası: {type(exc).__name__}: {exc}")

        if frontier:
            if source.content_kind == "ulke_bilgisi":
                logger.info(
                    "%s: %s country links indexed lazily after %s eager pages",
                    source.id,
                    len(frontier),
                    source.max_pages,
                )
            elif partial:
                logger.info(
                    "%s: priority refresh scanned %s pages; %s previously indexed pages remain in the full baseline",
                    source.id,
                    source.max_pages,
                    len(frontier),
                )
            else:
                errors.append(
                    f"{source.id}: güvenlik sayfa sınırına ulaşıldı ({source.max_pages}); {len(frontier)} sayfa sırada kaldı"
                )
        return len(seen), documents, errors

    async def _crawl_recent_trade_legislation(
        self,
        source: TicaretSource,
    ) -> tuple[int, list[TicaretDocument], list[str]]:
        """Index recent trade legislation from the official Justice service.

        Ministry landing pages can be updated after an Official Gazette issue.
        This independent official layer closes that gap without inventing
        titles, dates, document numbers or source links.
        """
        end_date = _utc_now()
        start_date = end_date - timedelta(days=45)
        title_markers = tuple(
            _search_key(value)
            for value in (
                "ithalat", "ihracat", "gümrük", "ticaret", "gözetim",
                "damping", "haksız rekabet", "korunma önlemi", "serbest bölge",
                "dahilde işleme", "hariçte işleme", "ürün güvenliği", "teknik düzenleme",
                "tüketici", "elektronik ticaret", "perakende", "ticari reklam",
                "kooperatif", "esnaf", "lisanslı depo", "hal hakem", "devlet yardımı",
                "ilave gümrük vergisi", "ek mali yükümlülük", "tarife kontenjanı",
                "gümrük tarife", "tarife cetveli", "tarife pozisyonu", "sübvansiyon",
            )
        )
        type_labels = {
            "TEBLIGLER": "Tebliğ",
            "CB_KARAR": "Cumhurbaşkanı Kararı",
            "CB_YONETMELIK": "Cumhurbaşkanlığı Yönetmeliği",
            "YONETMELIK": "Yönetmelik",
            "KKY": "Kurum Yönetmeliği",
        }
        documents_by_id: dict[str, TicaretDocument] = {}
        errors: list[str] = []
        page = 1
        pages_scanned = 0
        max_pages = 10

        while page <= max_pages:
            result = await self._bedesten.search_documents(
                mevzuat_tur_list=list(type_labels),
                resmi_gazete_tarihi_start=start_date.strftime("%d/%m/%Y"),
                resmi_gazete_tarihi_end=end_date.strftime("%d/%m/%Y"),
                page=page,
                page_size=20,
                sort_field="RESMI_GAZETE_TARIHI",
                sort_direction="desc",
            )
            if result.error_message:
                errors.append(f"{source.id}: {result.error_message}")
                break
            pages_scanned += 1
            for item in result.documents:
                title = _clean_text(item.mevzuat_adi)
                if not title or not any(marker in _search_key(title) for marker in title_markers):
                    continue
                type_info = item.mevzuat_tur if isinstance(item.mevzuat_tur, dict) else {}
                type_name = str(type_info.get("name") or item.mevzuat_tur or "").upper()
                publication_date = item.resmi_gazete_tarihi
                gazette_url = "https://resmigazete.gov.tr/"
                if publication_date:
                    try:
                        date_value = datetime.fromisoformat(publication_date.replace("Z", "+00:00"))
                        gazette_url = f"https://resmigazete.gov.tr/{date_value.strftime('%d.%m.%Y')}"
                    except ValueError:
                        pass
                document_url = item.url or (
                    "https://www.mevzuat.gov.tr/mevzuat?"
                    f"MevzuatNo={item.mevzuat_no}&MevzuatTur=9&MevzuatTertip={item.mevzuat_tertip or 5}"
                )
                document = TicaretDocument(
                    id=_stable_id(source.id, str(item.mevzuat_id)),
                    title=title[:500],
                    source_id=source.id,
                    content_kind=source.content_kind,
                    section="Resmî Gazete / Güncel Ticaret Mevzuatı",
                    document_type=type_labels.get(type_name, "Mevzuat"),
                    number=str(item.mevzuat_no),
                    publication_date=publication_date,
                    official_gazette=item.resmi_gazete_sayisi,
                    document_url=_canonical_document_url(document_url),
                    source_page_url=gazette_url,
                    file_type="html",
                    is_page=False,
                    context=(
                        f"Resmî Gazete sayı {item.resmi_gazete_sayisi or 'belirtilmedi'}; "
                        "başlık, tarih ve numara Adalet Bakanlığı Bedesten resmî mevzuat servisinden alınmıştır."
                    ),
                    metadata={
                        "bedesten_mevzuat_id": item.mevzuat_id,
                        "official_source": "bedesten.adalet.gov.tr/mevzuat",
                        "rolling_window_days": 45,
                    },
                )
                documents_by_id[document.id] = document

            total_pages = max(1, (result.total_results + 19) // 20)
            if page >= total_pages:
                break
            page += 1
            await asyncio.sleep(0.2)

        if page >= max_pages and result.total_results > max_pages * 20:
            errors.append(f"{source.id}: son 45 günlük mevzuat {max_pages * 20} kayıtlık güvenlik sınırını aştı")
        return pages_scanned, list(documents_by_id.values()), errors

    async def refresh_catalog(self, *, core_only: bool = False) -> TicaretCatalog:
        """Rebuild the complete catalogue from live official pages."""
        async with self._sync_lock:
            # Startup lifespan and the first MCP call may request the quick
            # bootstrap at the same instant. Reuse the just-built snapshot.
            if core_only and self._catalog is not None and time.monotonic() - self._catalog_monotonic < 60:
                return self._catalog
            self._syncing = True
            previous = self._catalog
            try:
                selected_sources = self.sources
                has_full_baseline = bool(
                    core_only and previous is not None and self._last_full_sync_monotonic > 0
                )
                if core_only:
                    core_ids = {
                        "resmi_gazete_guncel", "gumruk", "ihracat", "ithalat",
                        "ithalat_duyurular", "destekler",
                    }
                    selected_sources = [
                        source.model_copy(update={"max_pages": min(source.max_pages, 40)})
                        for source in self.sources
                        if source.id in core_ids
                    ]

                async def crawl(source: TicaretSource):
                    try:
                        if source.id == "resmi_gazete_guncel":
                            return source, await asyncio.wait_for(
                                self._crawl_recent_trade_legislation(source), timeout=90
                            )
                        return source, await asyncio.wait_for(
                            self._crawl_source(source, partial=has_full_baseline),
                            timeout=240,
                        )
                    except asyncio.TimeoutError:
                        return source, (0, [], [f"{source.id}: kaynak taraması 240 saniyelik süre sınırını aştı"])
                    except Exception as exc:
                        return source, (0, [], [f"{source.id}: kaynak taraması başarısız: {type(exc).__name__}: {exc}"])

                crawl_results = await asyncio.gather(*(crawl(source) for source in selected_sources))
                page_count = 0
                documents_by_id: dict[str, TicaretDocument] = {}
                errors: list[str] = []
                if core_only and previous:
                    selected_ids = {source.id for source in selected_sources}
                    for document in previous.documents:
                        if has_full_baseline or document.source_id not in selected_ids:
                            documents_by_id[document.id] = document

                for source, (pages, documents, source_errors) in crawl_results:
                    page_count += pages
                    errors.extend(source_errors)
                    for document in documents:
                        documents_by_id[document.id] = document

                documents = sorted(
                    documents_by_id.values(),
                    key=lambda item: (
                        _search_key(item.content_kind),
                        _search_key(item.section),
                        _search_key(item.title),
                        item.document_url,
                    ),
                )
                fingerprint_source = "\n".join(
                    f"{item.id}|{item.title}|{item.document_url}|{item.page_updated_at or ''}"
                    for item in documents
                )
                fingerprint = hashlib.sha256(fingerprint_source.encode("utf-8")).hexdigest()
                previous_ids = {item.id for item in previous.documents} if previous else set()
                current_ids = {item.id for item in documents}
                catalog = TicaretCatalog(
                    synced_at=_iso_now(),
                    fingerprint=fingerprint,
                    sources=self.sources,
                    pages_scanned=page_count,
                    documents=documents,
                    errors=errors[:100],
                    added_ids=sorted(current_ids - previous_ids),
                    removed_ids=sorted(previous_ids - current_ids),
                )
                self._catalog = catalog
                self._catalog_monotonic = time.monotonic()
                if not core_only:
                    self._last_full_sync_monotonic = self._catalog_monotonic
                self._next_sync_at = _utc_now() + timedelta(seconds=self.priority_sync_interval_seconds)
                logger.info(
                    "Ticaret catalogue synced: %s pages, %s documents, %s errors",
                    page_count,
                    len(documents),
                    len(errors),
                )
                return catalog
            finally:
                self._syncing = False

    async def get_catalog(self, *, force_refresh: bool = False) -> TicaretCatalog:
        if self._catalog is None:
            # A first user request must not wait for every country report page.
            # The operationally critical trees are small and provide an
            # immediately useful catalogue while the scheduled full refresh
            # continues in the background.
            return await self.refresh_catalog(core_only=True)
        full_age = time.monotonic() - self._last_full_sync_monotonic
        if force_refresh or full_age >= self.sync_interval_seconds:
            return await self.refresh_catalog()
        return self._catalog

    async def periodic_refresh_loop(self) -> None:
        """Refresh priority sources hourly and the complete catalogue less often."""
        while True:
            try:
                if self._catalog is None:
                    await self.refresh_catalog(core_only=True)
                full_sync_due = (
                    self._last_full_sync_monotonic == 0
                    or time.monotonic() - self._last_full_sync_monotonic >= self.sync_interval_seconds
                )
                await self.refresh_catalog(core_only=not full_sync_due)
            except asyncio.CancelledError:
                raise
            except Exception:
                logger.exception("Scheduled Ticaret catalogue refresh failed")
            await asyncio.sleep(self.priority_sync_interval_seconds)

    def status(self) -> TicaretCatalogStatus:
        catalog = self._catalog
        recent_documents = [
            document for document in (catalog.documents if catalog else [])
            if document.source_id == "resmi_gazete_guncel"
        ]
        latest_gazette_date = max(
            (document.publication_date or "" for document in recent_documents),
            default="",
        ) or None
        return TicaretCatalogStatus(
            ready=catalog is not None,
            syncing=self._syncing,
            last_synced_at=catalog.synced_at if catalog else None,
            next_scheduled_sync_at=self._next_sync_at.isoformat() if self._next_sync_at else None,
            sync_interval_seconds=self.priority_sync_interval_seconds,
            full_sync_interval_seconds=self.sync_interval_seconds,
            latest_official_gazette_date=latest_gazette_date,
            latest_official_gazette_documents=len(recent_documents),
            source_count=len(catalog.sources) if catalog else len(self.sources),
            pages_scanned=catalog.pages_scanned if catalog else 0,
            document_count=len(catalog.documents) if catalog else 0,
            fingerprint=catalog.fingerprint if catalog else None,
            added_since_previous_sync=len(catalog.added_ids) if catalog else 0,
            removed_since_previous_sync=len(catalog.removed_ids) if catalog else 0,
            errors=catalog.errors[:20] if catalog else [],
        )

    @staticmethod
    def _score_document(document: TicaretDocument, query: str) -> int:
        if not query:
            return 1
        query_key = _search_key(query).strip()
        tokens = [token for token in re.split(r"\W+", query_key) if len(token) >= 2]
        numeric_tokens = [token for token in tokens if any(ch.isdigit() for ch in token)]
        title = _search_key(document.title)
        haystack = _search_key(
            " ".join(
                filter(
                    None,
                    [
                        document.title,
                        document.section,
                        document.subsection,
                        document.document_type,
                        document.number,
                        document.publication_date,
                        document.context,
                        document.document_url,
                    ],
                )
            )
        )
        if numeric_tokens and any(token not in haystack for token in numeric_tokens):
            return 0
        if query_key and query_key in haystack:
            score = 120
        elif tokens and all(token in haystack for token in tokens):
            score = 65
        else:
            matched = sum(1 for token in tokens if token in haystack)
            required_matches = max(1, (len(tokens) + 1) // 2)
            if matched < required_matches:
                return 0
            score = matched * 10
        score += sum(12 for token in tokens if token in title)
        if document.is_page:
            score += 2
        if not document.is_repealed:
            score += 3
        return score

    @staticmethod
    def _is_report_document(document: TicaretDocument) -> bool:
        """Separate actual reports from navigation/contact pages in broad sources."""
        if document.source_id not in {
            "musavirlik_pazar",
            "musavirlik_blog_guncel",
            "yurtdisi_teskilati",
        }:
            return False
        haystack = _search_key(
            " ".join(
                filter(
                    None,
                    [
                        document.title,
                        document.section,
                        document.subsection,
                        document.document_type,
                        document.document_url,
                        document.source_page_url,
                    ],
                )
            )
        )
        return any(
            marker in haystack
            for marker in (
                "rapor",
                "pazar arastirmasi",
                "sektorel arastirma",
                "bulten",
                "/raporlar/",
                "/raporlar",
            )
        )

    @staticmethod
    def _country_path_parts(document: TicaretDocument) -> list[str]:
        parts = [part for part in urlsplit(document.document_url).path.strip("/").split("/") if part]
        try:
            root_index = [_search_key(part) for part in parts].index("yurtdisi-teskilati")
        except ValueError:
            return []
        return parts[root_index + 1:]

    @classmethod
    def _is_country_information_document(cls, document: TicaretDocument) -> bool:
        """Keep country/profile records; remove region and organisation navigation pages."""
        if document.source_id != "yurtdisi_teskilati":
            return False
        parts = cls._country_path_parts(document)
        if len(parts) < 2:
            return False
        if _search_key(parts[0]) in {
            "yurt-disi-temsilciliklerimiz",
            "uluslararasi-kuruluslar-nezdinde-daimi-temsilciliklerimiz",
        }:
            return False
        # Country report documents belong in the dedicated Reports view.
        if any("rapor" in _search_key(part) for part in parts[2:]):
            return False
        return True

    @classmethod
    def _matches_content_kinds(cls, document: TicaretDocument, kind_keys: set[str]) -> bool:
        if not kind_keys:
            return True
        for kind in kind_keys:
            if kind == "rapor" and cls._is_report_document(document):
                return True
            if kind == "ulke_bilgisi" and cls._is_country_information_document(document):
                return True
            if kind not in {"rapor", "ulke_bilgisi"} and _search_key(document.content_kind) == kind:
                return True
        return False

    @classmethod
    def _browse_priority(cls, document: TicaretDocument, kind_keys: set[str]) -> int:
        """Put useful leaf records before broad landing pages when browsing."""
        if "rapor" in kind_keys and cls._is_report_document(document):
            title = _search_key(document.title)
            priority = 40
            if "rapor" in title or "pazar arastirmasi" in title:
                priority += 45
            if document.file_type in {"pdf", "doc", "docx", "xls", "xlsx"}:
                priority += 35
            if not document.is_page:
                priority += 15
            return priority
        if "ulke_bilgisi" in kind_keys and cls._is_country_information_document(document):
            parts = cls._country_path_parts(document)
            last = _search_key(parts[-1]) if parts else ""
            if len(parts) == 2:
                return 130
            return {
                "genel-bilgiler": 120,
                "ulke-profili": 110,
                "pazar-bilgileri": 100,
                "potansiyel-urun-matrisleri": 85,
                "ikili-anlasmalar": 60,
                "faydali-linkler": 45,
            }.get(last, 35 if document.file_type == "pdf" else 20)
        return 0

    async def search(
        self,
        *,
        query: str = "",
        content_kinds: Optional[list[str]] = None,
        source_ids: Optional[list[str]] = None,
        document_types: Optional[list[str]] = None,
        year: Optional[int] = None,
        include_repealed: bool = False,
        offset: int = 0,
        limit: int = 20,
    ) -> TicaretSearchResult:
        catalog = await self.get_catalog()
        kind_keys = {_search_key(value) for value in (content_kinds or [])}
        source_keys = {_search_key(value) for value in (source_ids or [])}
        type_keys = {_search_key(value) for value in (document_types or [])}
        excluded_repealed = 0
        scored: list[tuple[int, TicaretDocument]] = []

        for document in catalog.documents:
            if not self._matches_content_kinds(document, kind_keys):
                continue
            if source_keys and _search_key(document.source_id) not in source_keys:
                continue
            if type_keys and _search_key(document.document_type) not in type_keys:
                continue
            if year and str(year) not in " ".join(
                filter(None, [document.publication_date, document.page_updated_at, document.number, document.title, document.source_page_url])
            ):
                continue
            if document.is_repealed and not include_repealed:
                excluded_repealed += 1
                continue
            score = self._score_document(document, query)
            if score:
                scored.append((score + self._browse_priority(document, kind_keys), document))

        scored.sort(
            key=lambda pair: (
                pair[0],
                pair[1].page_updated_at or "",
                pair[1].publication_date or "",
                pair[1].title,
            ),
            reverse=True,
        )
        total = len(scored)
        selected = [document for _, document in scored[offset: offset + limit]]
        # Special views collect records from more than one official source
        # tree. Label them with the selected view without mutating the stored
        # catalogue record used for full-text retrieval.
        if len(kind_keys) == 1 and next(iter(kind_keys)) in {"rapor", "ulke_bilgisi"}:
            display_kind = next(iter(kind_keys))
            selected = [document.model_copy(update={"content_kind": display_kind}) for document in selected]
        return TicaretSearchResult(
            documents=selected,
            total_results=total,
            offset=offset,
            limit=limit,
            catalog_synced_at=catalog.synced_at,
            catalog_fingerprint=catalog.fingerprint,
            excluded_repealed=excluded_repealed,
            note=(
                "Sonuçlar canlı resmî kaynak kataloğunun başlık, tablo alanları ve sayfa özetlerinde aranmıştır. "
                "Bir kaydın tam metni için get_ticaret_document; birden çok belgenin içeriğini taramak için "
                "search_ticaret_content aracını kullanın. Hukuki değerlendirmede kaynak URL'sini ve yürürlük durumunu doğrulayın."
            ),
        )

    async def _find_document(self, document_id: str) -> TicaretDocument:
        catalog = await self.get_catalog()
        for document in catalog.documents:
            if document.id == document_id:
                return document
        raise ValueError(f"Belge bulunamadı: {document_id}. Önce search_ticaret_catalog aracını kullanın.")

    @staticmethod
    def _normalise_mevzuat_download_url(url: str) -> str:
        parsed = urlsplit(url)
        if not (parsed.hostname or "").lower().endswith("mevzuat.gov.tr"):
            return url
        query = dict(parse_qsl(parsed.query))
        code_match = re.search(r"MevzuatKod=(\d+)\.(\d+)\.([\w.-]+)", url, re.IGNORECASE)
        if code_match:
            return f"https://www.mevzuat.gov.tr/MevzuatMetin/{code_match.group(1)}.{code_match.group(2)}.{code_match.group(3)}.pdf"
        if query.get("MevzuatNo") and query.get("MevzuatTur") and query.get("MevzuatTertip"):
            return (
                "https://www.mevzuat.gov.tr/MevzuatMetin/"
                f"{query['MevzuatTur']}.{query['MevzuatTertip']}.{query['MevzuatNo']}.pdf"
            )
        # A number of Ministry pages still expose http:// links. Keep TLS
        # verification enabled and canonicalise those links to HTTPS.
        return urlunsplit(("https", parsed.netloc, parsed.path, parsed.query, ""))

    @staticmethod
    def _mevzuat_number_from_url(url: str) -> str | None:
        parsed = urlsplit(url)
        query = dict(parse_qsl(parsed.query))
        if query.get("MevzuatNo"):
            return query["MevzuatNo"]
        match = re.search(r"/\d+\.\d+\.([\w-]+)\.pdf$", unquote(parsed.path), re.IGNORECASE)
        return match.group(1) if match else None

    async def _bedesten_fallback(self, document: TicaretDocument) -> tuple[str, str, list[str]] | None:
        """Read a mevzuat.gov.tr document from the official Adalet mirror.

        Some legacy Ministry links currently present an invalid TLS chain. We do
        not weaken TLS verification; the same numbered legislation is selected
        from Bedesten and title-matched before its text is returned.
        """
        number = self._mevzuat_number_from_url(document.document_url) or document.number
        if not number:
            return None
        result = await self._bedesten.search_documents(mevzuat_no=str(number), page_size=20)
        if result.error_message or not result.documents:
            return None

        title_key = _search_key(document.title)
        title_tokens = {token for token in re.split(r"\W+", title_key) if len(token) >= 3}

        def candidate_score(candidate: Any) -> tuple[int, int]:
            candidate_key = _search_key(candidate.mevzuat_adi)
            candidate_tokens = {token for token in re.split(r"\W+", candidate_key) if len(token) >= 3}
            exact_number = int(str(candidate.mevzuat_no).strip() == str(number).strip())
            overlap = len(title_tokens & candidate_tokens)
            exact_title = int(bool(title_key) and title_key == candidate_key)
            return exact_number * 100 + exact_title * 50 + overlap, -len(candidate_key)

        selected = max(result.documents, key=candidate_score)
        score, _ = candidate_score(selected)
        if score < 101:  # exact number plus at least one title token
            return None
        content = await self._bedesten.get_document_plain_text(selected.mevzuat_id)
        if not content:
            return None
        resolved = f"https://bedesten.adalet.gov.tr/mevzuat (mevzuatId={selected.mevzuat_id})"
        warning = (
            "Ticaret Bakanlığı sayfasındaki eski mevzuat.gov.tr bağlantısının güvenli indirmesi başarısız olduğu için "
            "tam metin, numara ve başlık eşleştirmesi yapılarak Adalet Bakanlığı Bedesten resmî servisinden alındı."
        )
        return content, resolved, [warning]

    async def _download(self, url: str) -> tuple[bytes, str, str]:
        url = self._normalise_mevzuat_download_url(url)
        parsed = urlsplit(url)
        if not _is_official_content_host(parsed.hostname):
            raise ValueError(
                "Tam metin indirme yalnızca ticaret.gov.tr, mevzuat.gov.tr ve resmigazete.gov.tr resmî alan adları için açıktır. "
                "Haricî veri kaynağına kayıt içindeki document_url üzerinden erişin."
            )
        async with self._http.stream("GET", url) as response:
            response.raise_for_status()
            resolved = str(response.url)
            if not _is_official_content_host(urlsplit(resolved).hostname):
                raise ValueError("Belge resmî alan adı dışına yönlendirildi; güvenlik nedeniyle indirme durduruldu.")
            length = response.headers.get("content-length")
            if length and int(length) > self.max_download_bytes:
                raise ValueError(f"Belge güvenli indirme sınırını aşıyor ({self.max_download_bytes} bayt).")
            chunks: list[bytes] = []
            total = 0
            async for chunk in response.aiter_bytes():
                total += len(chunk)
                if total > self.max_download_bytes:
                    raise ValueError(f"Belge güvenli indirme sınırını aşıyor ({self.max_download_bytes} bayt).")
                chunks.append(chunk)
            return b"".join(chunks), response.headers.get("content-type", ""), resolved

    def _html_to_text(self, data: bytes, base_url: str = "") -> str:
        soup = BeautifulSoup(data, "lxml")
        for node in soup.select("script, style, noscript, nav, header, footer"):
            node.decompose()
        content = self._content_container(soup)
        # Plain-text conversion normally discards every href. Preserve the
        # official evidence chain so the reader can render document and annex
        # links as real actions instead of inert labels.
        for anchor in content.select("a[href]"):
            raw_href = (anchor.get("href") or "").strip()
            if not raw_href or raw_href.startswith(("#", "javascript:", "mailto:", "tel:")):
                continue
            resolved_link = urljoin(base_url, raw_href) if base_url else raw_href
            if urlsplit(resolved_link).scheme not in {"http", "https"}:
                continue
            label = _clean_text(anchor.get_text(" ", strip=True)) or "Resmî bağlantı"
            anchor.replace_with(f"{label} — {resolved_link}")
        # Preserve table rows and paragraph boundaries for legal/data analysis.
        for br in content.find_all("br"):
            br.replace_with("\n")
        for row in content.find_all("tr"):
            cells = [_clean_text(cell.get_text(" ", strip=True)) for cell in row.find_all(["th", "td"], recursive=False)]
            row.replace_with("\n" + " | ".join(value for value in cells if value) + "\n")
        return re.sub(r"\n{3,}", "\n\n", content.get_text("\n", strip=True)).strip()

    @staticmethod
    def _convert_legacy_office(data: bytes, extension: str) -> str | None:
        """Extract text from pre-OOXML Office files using sandboxed CLI readers.

        MarkItDown intentionally does not support legacy ``.doc``/``.ppt`` files.
        Debian's small, read-only converters cover the official Ministry archive
        without requiring a full office suite in the production image.
        """
        command_name = {
            ".doc": "antiword",
            ".ppt": "catppt",
            ".xls": "xls2csv",
        }.get(extension)
        if not command_name:
            return None
        executable = shutil.which(command_name)
        if not executable:
            return None
        temp_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(suffix=extension, delete=False) as handle:
                handle.write(data)
                temp_path = Path(handle.name)
            command = [executable]
            if command_name == "antiword":
                command.extend(["-m", "UTF-8.txt"])
            command.append(str(temp_path))
            # ``command_name`` comes from the fixed extension map above.
            completed = subprocess.run(  # nosec B603
                command,
                capture_output=True,
                check=False,
                timeout=30,
            )
            if completed.returncode != 0:
                logger.warning(
                    "Legacy %s conversion failed with %s: %s",
                    extension,
                    command_name,
                    completed.stderr.decode("utf-8", errors="replace")[:500],
                )
                return None
            text = completed.stdout.decode("utf-8", errors="replace").replace("\x00", "")
            return re.sub(r"\n{3,}", "\n\n", text).strip() or None
        except (OSError, subprocess.SubprocessError) as exc:
            logger.warning("Legacy %s conversion failed: %s", extension, exc)
            return None
        finally:
            if temp_path:
                temp_path.unlink(missing_ok=True)

    def _convert_binary(self, data: bytes, extension: str, url: str) -> tuple[str, list[str]]:
        warnings: list[str] = []
        if extension == ".zip":
            parts: list[str] = []
            total_uncompressed = 0
            with zipfile.ZipFile(io.BytesIO(data)) as archive:
                members = [item for item in archive.infolist() if not item.is_dir()]
                parts.append("# Arşiv İçeriği\n" + "\n".join(f"- {item.filename}" for item in members))
                for item in members:
                    member_ext = Path(item.filename).suffix.lower()
                    if member_ext not in _DOCUMENT_EXTENSIONS - {".zip"}:
                        continue
                    if item.file_size > 15 * 1024 * 1024:
                        warnings.append(f"Arşiv üyesi boyut sınırı nedeniyle atlandı: {item.filename}")
                        continue
                    total_uncompressed += item.file_size
                    if total_uncompressed > 60 * 1024 * 1024:
                        warnings.append("Arşivin kalan üyeleri toplam açılmış boyut sınırı nedeniyle atlandı.")
                        break
                    member_data = archive.read(item)
                    try:
                        text, member_warnings = self._convert_binary(
                            member_data,
                            member_ext,
                            f"{url}#{quote(item.filename)}",
                        )
                        warnings.extend(f"{item.filename}: {warning}" for warning in member_warnings)
                        if text:
                            parts.append(f"\n# {item.filename}\n{text}")
                    except Exception as exc:
                        warnings.append(f"Arşiv üyesi dönüştürülemedi: {item.filename} ({type(exc).__name__})")
            return "\n\n".join(parts), warnings

        if extension in {".doc", ".xls", ".ppt"}:
            legacy_text = self._convert_legacy_office(data, extension)
            if legacy_text:
                return legacy_text, warnings

        try:
            result = self._converter.convert_stream(io.BytesIO(data), file_extension=extension or None, url=url)
            text = (result.text_content or "").strip()
            if not text:
                warnings.append("Belgeden metin çıkarılamadı; taranmış görüntü/OCR gerekebilir.")
            return text, warnings
        except Exception as exc:
            warnings.append(f"Belge dönüştürülemedi: {type(exc).__name__}: {exc}")
            return "", warnings

    async def _extract_document_text(self, document: TicaretDocument) -> tuple[str, str, list[str]]:
        cached = self._content_cache.get(document.id)
        if cached and time.monotonic() < cached[0]:
            self._content_cache.move_to_end(document.id)
            return cached[1], cached[2], list(cached[3])

        try:
            data, content_type, resolved_url = await self._download(document.document_url)
        except httpx.HTTPError:
            if (urlsplit(document.document_url).hostname or "").lower().endswith("mevzuat.gov.tr"):
                fallback = await self._bedesten_fallback(document)
                if fallback:
                    text, resolved_url, warnings = fallback
                    self._content_cache[document.id] = (
                        time.monotonic() + self._content_cache_ttl,
                        text,
                        resolved_url,
                        warnings,
                    )
                    return text, resolved_url, warnings
            raise
        extension = Path(unquote(urlsplit(resolved_url).path)).suffix.lower()
        lowered_type = content_type.lower()
        sniffed_extension = _sniff_document_extension(data, content_type)
        if not extension or extension not in _DOCUMENT_EXTENSIONS:
            extension = sniffed_extension or extension
        elif sniffed_extension == ".html":
            # Some official download endpoints return an HTML notice while
            # retaining the requested file suffix.
            extension = ".html"
        if "html" in lowered_type or extension in {".htm", ".html"}:
            text = self._html_to_text(data, resolved_url)
            warnings: list[str] = []
        elif extension in {".txt", ".csv", ".json", ".xml"}:
            text = data.decode("utf-8", errors="replace")
            warnings = []
        else:
            text, warnings = await asyncio.to_thread(self._convert_binary, data, extension, resolved_url)

        self._content_cache[document.id] = (
            time.monotonic() + self._content_cache_ttl,
            text,
            resolved_url,
            warnings,
        )
        self._content_cache.move_to_end(document.id)
        while len(self._content_cache) > self._content_cache_limit:
            self._content_cache.popitem(last=False)
        return text, resolved_url, warnings

    async def get_document_content(
        self,
        document_id: str,
        *,
        offset: int = 0,
        max_characters: int = 40000,
    ) -> TicaretDocumentContent:
        document = await self._find_document(document_id)
        text, resolved_url, warnings = await self._extract_document_text(document)
        offset = max(0, min(offset, len(text)))
        max_characters = max(1000, min(max_characters, 100000))
        content = text[offset: offset + max_characters]
        return TicaretDocumentContent(
            document=document,
            content=content,
            total_characters=len(text),
            offset=offset,
            returned_characters=len(content),
            truncated=offset + len(content) < len(text),
            resolved_url=resolved_url,
            fetched_at=_iso_now(),
            warnings=warnings,
        )

    @staticmethod
    def _excerpts(text: str, query: str, *, max_excerpts: int = 5, radius: int = 420) -> tuple[int, list[str]]:
        search_text = _search_key(text)
        query_key = _search_key(query).strip()
        terms = [query_key] if query_key and query_key in search_text else [
            token for token in re.split(r"\W+", query_key) if len(token) >= 2
        ]
        positions: list[int] = []
        occurrence_count = 0
        for term in terms:
            start = 0
            while term and (position := search_text.find(term, start)) >= 0:
                occurrence_count += 1
                positions.append(position)
                start = position + max(1, len(term))
        positions = sorted(set(positions))
        excerpts = []
        last_end = -1
        for position in positions:
            start = max(0, position - radius)
            end = min(len(text), position + radius)
            if start <= last_end:
                continue
            excerpt = text[start:end].strip()
            if start:
                excerpt = "…" + excerpt
            if end < len(text):
                excerpt += "…"
            excerpts.append(excerpt)
            last_end = end
            if len(excerpts) >= max_excerpts:
                break
        return occurrence_count, excerpts

    async def search_content(
        self,
        *,
        query: str,
        document_ids: Optional[list[str]] = None,
        content_kinds: Optional[list[str]] = None,
        source_ids: Optional[list[str]] = None,
        year: Optional[int] = None,
        include_repealed: bool = False,
        max_documents_to_scan: int = 12,
        max_results: int = 10,
    ) -> TicaretContentSearchResult:
        if not query.strip():
            raise ValueError("Tam metin araması için query boş olamaz.")
        catalog = await self.get_catalog()
        if document_ids:
            requested = set(document_ids)
            candidates = [item for item in catalog.documents if item.id in requested]
        else:
            metadata = await self.search(
                query=query,
                content_kinds=content_kinds,
                source_ids=source_ids,
                year=year,
                include_repealed=include_repealed,
                offset=0,
                limit=100,
            )
            candidates = metadata.documents
            # When metadata does not contain the term, scan filtered HTML index
            # pages too; this is useful for consolidated contact/data pages.
            if not candidates:
                kind_keys = {_search_key(value) for value in (content_kinds or [])}
                source_keys = {_search_key(value) for value in (source_ids or [])}
                candidates = [
                    item for item in catalog.documents
                    if item.is_page
                    and (not kind_keys or _search_key(item.content_kind) in kind_keys)
                    and (not source_keys or _search_key(item.source_id) in source_keys)
                    and (include_repealed or not item.is_repealed)
                ]

        candidate_count = len(candidates)
        scan_limit = max(1, min(max_documents_to_scan, 25))
        candidates = candidates[:scan_limit]
        semaphore = asyncio.Semaphore(4)

        async def scan(document: TicaretDocument) -> tuple[TicaretContentMatch | None, str | None]:
            async with semaphore:
                try:
                    text, _, _ = await self._extract_document_text(document)
                    count, excerpts = self._excerpts(text, query)
                    if not count:
                        return None, None
                    return TicaretContentMatch(
                        document_id=document.id,
                        title=document.title,
                        section=document.section,
                        source_page_url=document.source_page_url,
                        document_url=document.document_url,
                        occurrence_count=count,
                        excerpts=excerpts,
                    ), None
                except Exception as exc:
                    return None, f"{document.id}: {type(exc).__name__}: {exc}"

        scanned = await asyncio.gather(*(scan(document) for document in candidates))
        matches = [match for match, _ in scanned if match]
        matches.sort(key=lambda item: item.occurrence_count, reverse=True)
        failures = [error for _, error in scanned if error]
        return TicaretContentSearchResult(
            query=query,
            matches=matches[: max(1, min(max_results, 20))],
            scanned_documents=len(candidates),
            candidate_documents=candidate_count,
            failed_documents=failures,
            catalog_synced_at=catalog.synced_at,
            coverage_note=(
                f"Bu çağrı {candidate_count} adayın {len(candidates)} tanesini tam metin olarak taradı. "
                "Kapsamlı hukuki araştırmada önce katalog filtrelerini daraltın, sonra dönen belge kimliklerini "
                "document_ids ile gruplar halinde tarayın. Sonuçlar bilgilendirme amaçlıdır; yürürlük ve değişiklik "
                "durumunu resmî kaynak URL'lerinden teyit edin."
            ),
        )

    async def list_sources(self) -> dict[str, Any]:
        catalog = await self.get_catalog()
        counts: dict[str, int] = {}
        pages: dict[str, int] = {}
        for document in catalog.documents:
            counts[document.source_id] = counts.get(document.source_id, 0) + 1
            if document.is_page:
                pages[document.source_id] = pages.get(document.source_id, 0) + 1
        layers: dict[str, dict[str, int]] = {}
        content_kinds = sorted({source.content_kind for source in catalog.sources})
        for kind in content_kinds:
            matching = [
                document
                for document in catalog.documents
                if self._matches_content_kinds(document, {_search_key(kind)})
            ]
            layers[kind] = {
                "sources": len({document.source_id for document in matching}),
                "documents": len(matching),
                "pages": sum(1 for document in matching if document.is_page),
            }
        return {
            "catalog_synced_at": catalog.synced_at,
            "layers": layers,
            "sources": [
                {
                    **source.model_dump(),
                    "documents": counts.get(source.id, 0),
                    "pages": pages.get(source.id, 0),
                }
                for source in catalog.sources
            ],
            "content_kinds": content_kinds,
            "errors": catalog.errors[:20],
        }
